# Generated by Django 2.2.3 on 2019-08-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=160, verbose_name='サイト名')),
                ('site_description', models.TextField(max_length=240, verbose_name='サイトの説明')),
                ('ogp_iamge', models.ImageField(blank=True, max_length=320, upload_to='uploads/', verbose_name='OGP画像')),
                ('profile_icon', models.ImageField(blank=True, max_length=320, upload_to='uploads/', verbose_name='プロフィール画像')),
                ('profile_info', models.TextField(max_length=240, verbose_name='プロフィール情報')),
                ('ga_tag', models.TextField(blank=True, max_length=600, verbose_name='GoogleAnalyticsタグ')),
                ('email', models.CharField(blank=True, max_length=240, verbose_name='メールアドレス')),
                ('twitter', models.CharField(blank=True, max_length=240, verbose_name='Twitter')),
                ('github', models.CharField(blank=True, max_length=240, verbose_name='GitHub')),
                ('is_public', models.BooleanField(default=True, verbose_name='検索エンジンに登録する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'サイト基本情報',
                'verbose_name_plural': 'サイト基本情報',
            },
        ),
    ]
