# Generated by Django 2.2.3 on 2019-08-31 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='ogp_iamge',
            new_name='ogp_image',
        ),
    ]
