#! /bin/bash

export PATH=$PATH:$HOME/.local/bin

if [[ "$TRAVIS_BRANCH" == "master" ]]; then
  docer --version
  pip install --user awscli
  aws ecr get-login --region ap-northeast-1
  docker build -t 
